version: '3.8'

# Docker compose file to stand up a local mongodb database
# You can then open the mongo-express server to browse the collections
# from 8081 port on your local machine
# this is strictly for local development ONLY

services:
  mongo:
    image: mongo
    volumes:
      - db_data:/data/db
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

volumes:
  db_data:
